/**
 * @file        packages/client/src/udev.js
 * @description Renders this Client instance's udev rules from its hw.* config and installs them
 *              (write rule file, reload, trigger, settle) — replaces the static udev/99-thub.rules (README §8.2)
 *
 * @author      Andrian Yablonskyy
 * @copyright   Copyright (c) 2026 Andrian Yablonskyy. All rights reserved.
 *
 * This file is part of TestHub and is proprietary and confidential.
 * Unauthorized copying, modification, distribution, or use of this file,
 * via any medium, is strictly prohibited without prior written permission
 * from AdSystem.PRO.
 */

'use strict';

const fs = require('node:fs'),
  path = require('node:path'),
  { execFileSync } = require('node:child_process');

const RULES_DIR = '/etc/udev/rules.d',
  SETTLE_TIMEOUT_SEC = 10,

  // Per-kind match defaults: common adapters. Each hw-devices.* entry can override vendorId/productId/subsystem.
  // UARTs match the tty node (what serialport opens), not the raw USB
  // device; ST-Links match the USB device (st-flash talks libusb).
  KIND_DEFAULTS = {
    stlink: { subsystem: 'usb', vendorId: '0483', productId: '3748' }, // ST-Link/V2
    uart: { subsystem: 'tty', vendorId: '0403', productId: '6001' }, // FTDI FT232R
    usb: { subsystem: 'usb', vendorId: '0483', productId: '5740' } // STM32 CDC (DUT's own USB)
  },
  LISTS = [['stlinks', 'stlink'], ['uarts', 'uart'], ['usbs', 'usb']],

  // uhubctl (hw-devices.usbPower, README §8.7) switches a port through its
  // hub's sysfs `<port>/disable` file (Linux 6+) or over libusb (older):
  // the service runs as an ordinary user in plugdev, so give that group
  // both — for every USB hub, since uhubctl also switches a USB3 hub's
  // USB2 twin, whose location isn't in the config.
  HUB_POWER_RULE = 'SUBSYSTEM=="usb", DRIVER=="usb", ATTR{bDeviceClass}=="09", MODE="0664", GROUP="plugdev", ' +
    'RUN+="/bin/sh -c \'chgrp -f plugdev $sys$devpath/*-port*/disable; chmod -f g+w $sys$devpath/*-port*/disable; true\'"';

function rulesFile(instance){
  return path.join(RULES_DIR, `99-thub-${instance}.rules`);
}

// Values end up inside "..." in a udev rule — refuse anything that could
// break out of the quotes or smuggle in another key.
function assertRuleValue(field, value){
  if (typeof value !== 'string' || !/^[\w.:+/-]+$/.test(value)){
    throw new Error(`${field} must be a non-empty string of [A-Za-z0-9_.:+/-], got ${JSON.stringify(value)}`);
  }
  return value;
}

function hexId(field, value){
  const v = assertRuleValue(field, String(value)).toLowerCase();
  if (!/^[0-9a-f]{4}$/.test(v)){
    throw new Error(`${field} must be a 4-digit hex USB id, got ${JSON.stringify(value)}`);
  }
  return v;
}

// One rule per hw.* entry that says where the device is plugged in
// (`devpath`, the USB port path as `udevadm info -a` shows ATTRS{devpath}).
// Entries without `devpath` are left to whatever already provides their
// `path` (a manual rule, or a plain /dev node) — so they get no rule here.
function ruleLines(hw){
  const lines = [];
  for (const [list, kind]of LISTS){
    (hw[list] || []).forEach((entry, i) => {
      if (entry.devpath === undefined){
        return;
      }
      const field = `hw.${list}[${i}]`,
        defaults = KIND_DEFAULTS[kind],
        devpath = assertRuleValue(`${field}.devpath`, String(entry.devpath)),
        vendorId = hexId(`${field}.vendorId`, entry.vendorId ?? defaults.vendorId),
        productId = hexId(`${field}.productId`, entry.productId ?? defaults.productId),
        subsystem = assertRuleValue(`${field}.subsystem`, entry.subsystem ?? defaults.subsystem);
      if (typeof entry.path !== 'string' || !entry.path.startsWith('/dev/')){
        throw new Error(`${field}.path must be under /dev/ to get a udev symlink, got ${JSON.stringify(entry.path)}`);
      }
      const symlink = assertRuleValue(`${field}.path`, entry.path.slice('/dev/'.length)),
        // ATTR{devpath} for a usb device itself, ATTRS{devpath} (a parent)
        // for a tty — ATTRS keys must all match on the same parent, and
        // idVendor/idProduct/devpath all live on the usb_device.
        devpathKey = subsystem === 'usb' ? 'ATTR{devpath}' : 'ATTRS{devpath}';
      lines.push(
        `SUBSYSTEM=="${subsystem}", ATTRS{idVendor}=="${vendorId}", ATTRS{idProduct}=="${productId}", ` +
          `${devpathKey}=="${devpath}", SYMLINK+="${symlink}"`
      );
    });
  }
  if (hw.usbPower?.ports?.length){
    lines.push(HUB_POWER_RULE);
  }
  return lines;
}

// null when this instance needs no rules at all (SW Client, or no entry
// with a devpath and no USB power ports) — its rule file, if any, is then removed.
function renderRules({ instance, type, hw }){
  const lines = type === 'hw' ? ruleLines(hw || {}) : [];
  if (!lines.length){
    return null;
  }
  return [
    `# Generated by thub-client for instance "${instance}" from its config's hw.* section.`,
    '# Rewritten on every Client start — edit the config, not this file.',
    ...lines,
    ''
  ].join('\n');
}

function readFileOrNull(file){
  try {
    return fs.readFileSync(file, 'utf8');
  }
  catch {
    return null;
  }
}

function isRoot(){
  return typeof process.getuid === 'function' && process.getuid() === 0;
}

// Symlinks this instance's rules claim that another instance's rule file
// (or the legacy static one) also claims — udev would pick either one.
function findConflicts(instance, content){
  const own = new Set([...content.matchAll(/SYMLINK\+="([^"]+)"/g)].map((m) => m[1])),
    conflicts = [];
  let files = [];
  try {
    files = fs.readdirSync(RULES_DIR).filter((f) => /^99-thub(-.+)?\.rules$/.test(f));
  }
  catch {
    return conflicts;
  }
  for (const f of files){
    const file = path.join(RULES_DIR, f);
    if (file === rulesFile(instance)){
      continue;
    }
    for (const [, link]of (readFileOrNull(file) || '').matchAll(/^[^#]*SYMLINK\+="([^"]+)"/gm)){
      if (own.has(link)){
        conflicts.push({ file, symlink: link });
      }
    }
  }
  return conflicts;
}

// Brings /etc/udev/rules.d/99-thub-<instance>.rules in line with the
// config: writes (or removes) it only when it differs, then reloads udev
// and re-triggers USB/tty devices so the symlinks exist before the Client
// reports its capabilities. Returns what it did:
//   skipped    — not Linux
//   unchanged  — file already matches the config
//   updated    — file written/removed and udev reloaded
//   needs-root — a change is needed but this process can't make it
function syncUdevRules(cfg, { log = console } = {}){
  if (process.platform !== 'linux'){
    return { status: 'skipped' };
  }
  const file = rulesFile(cfg.instance),
    content = renderRules(cfg),
    current = readFileOrNull(file);

  if (content){
    for (const { file: other, symlink }of findConflicts(cfg.instance, content)){
      log.warn(`udev: ${other} also defines /dev/${symlink}.`);
    }
  }

  if (content === current){
    return { status: 'unchanged', file };
  }
  if (!isRoot()){
    return { status: 'needs-root', file };
  }

  if (content){
    fs.writeFileSync(file, content, { mode: 0o644 });
  }
  else {
    fs.rmSync(file, { force: true });
  }
  execFileSync('udevadm', ['control', '--reload'], { stdio: 'ignore' });
  // `change`, not `add`: re-applies the rules (and so the symlinks)
  // without making anything else treat the devices as newly plugged in.
  for (const subsystem of ['usb', 'tty']){
    execFileSync('udevadm', ['trigger', '--action=change', `--subsystem-match=${subsystem}`], { stdio: 'ignore' });
  }
  execFileSync('udevadm', ['settle', `--timeout=${SETTLE_TIMEOUT_SEC}`], { stdio: 'ignore' });
  log.log(content ? `udev: installed ${file}` : `udev: removed ${file} (no hw devices with a devpath)`);
  return { status: 'updated', file };
}

module.exports = { renderRules, syncUdevRules, rulesFile, HUB_POWER_RULE };

// systemd ExecStartPre=+ entry point (runs as root, before the daemon
// drops to its own user): `node udev.js --config <path>`.
// Never fails the unit — a bad udev setup shows up as missing devices on
// the resource card, which beats a Client that won't start at all.
if (require.main === module){
  const { loadDeviceConfig } = require('./config'),
    argv = process.argv.slice(2),
    flag = (name) => {
      const i = argv.indexOf(name);
      return i >= 0 ? argv[i + 1] : undefined;
    };
  try {
    const { status, file } = syncUdevRules(loadDeviceConfig(flag('--config') || process.env.THUB_CLIENT_CONFIG));
    if (status === 'needs-root'){
      console.warn(`udev: ${file} is out of date but this is not running as root`);
    }
  }
  catch (err){
    console.error(`udev: ${err.message}`);
  }
}
